pool:
  vmImage: 'Ubuntu 16.04'

steps:

- script: echo "@infragistics:registry=$(npmRegistry)" >> ~/.npmrc 
  displayName: 'Npm add registry'

- script: echo "$(igScope):always-auth=true" >> ~/.npmrc
  displayName: 'Npm config'

- script: echo "$(igScope):_auth=$(token)" >> ~/.npmrc
  displayName: 'Npm config auth'

- script: npm install
  displayName: 'Install dependencies'
  env:
    AZURE_PIPELINES: "true"

- script: npm run lint
  displayName: 'Run lint'

- script: npm run build
  displayName: 'Generate live editing and build samples'
  env:
    NODE_OPTIONS: "--max_old_space_size=4096"
