pool:
  vmImage: 'Ubuntu 16.04'

steps:

- task: NpmAddRegistry@1
  inputs:
    command: 'custom'
    workingDir: '$(Build.SourcesDirectory)'
    customCommand: 'config set @infragistics:registry $(npmRegistry)'

- task: NpmConfig@1
  inputs:
    command: 'custom'
    workingDir: '$(Build.SourcesDirectory)'
    customCommand: 'config set always-auth=true --scope:@infragistics'

- task: NpmConfigAuth@1
  inputs:
    command: 'custom'
    workingDir: '$(Build.SourcesDirectory)'
    customCommand: 'config set _auth=$(token) --scope:@infragistics'

- script: npm install
  displayName: 'Install dependencies'
  env:
    AZURE_PIPELINES: "true"

- script: npm run lint
  displayName: 'Run lint'

- script: npm run build
  displayName: 'Generate live editing and build samples'
  env:
    NODE_OPTIONS: "--max_old_space_size=4096"
